/**
 * Refreshes the self-hosted font subsets in site/fonts + site/css/fonts.css.
 *
 * Run only when the type stack changes — the output is committed, so a normal
 * build or deploy never needs network access.
 *
 *   node scripts/fetch-fonts.mjs
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SITE = path.resolve(__dirname, "..", "site");

const API =
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@400;500;600;700&family=Prata&display=swap";

// Ukrainian needs cyrillic; latin covers brand words, numerals and punctuation.
const KEEP = new Set(["cyrillic", "cyrillic-ext", "latin", "latin-ext"]);

const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const css = execFileSync("curl", ["-sS", "--fail", "-A", UA, API], { encoding: "utf8" });

const faces = css
  .split("/*")
  .slice(1)
  .map((chunk) => "/*" + chunk)
  .map((block) => {
    const subset = block.match(/^\/\*\s*([a-z-]+)\s*\*\//)?.[1];
    if (!subset || !KEEP.has(subset)) return null;
    return {
      subset,
      family: block.match(/font-family: '([^']+)'/)[1],
      weight: block.match(/font-weight: (\d+)/)[1],
      url: block.match(/url\((https:[^)]+)\)/)[1],
      block: block.replace(/^\/\*[^*]*\*\/\s*/, "").trim(),
    };
  })
  .filter(Boolean);

fs.rmSync(path.join(SITE, "fonts"), { recursive: true, force: true });
fs.mkdirSync(path.join(SITE, "fonts"), { recursive: true });

// Several weights of a variable family share one file — download each once.
const names = new Map();
let n = 0;
for (const face of faces) {
  if (names.has(face.url)) continue;
  n += 1;
  const name = `${face.family.toLowerCase().replace(/\s+/g, "-")}-${face.subset}-${n}.woff2`;
  names.set(face.url, name);
  execFileSync("curl", ["-sS", "--fail", "-o", path.join(SITE, "fonts", name), face.url]);
}

const out = faces.map(
  (f) =>
    `/* ${f.family} ${f.weight} · ${f.subset} */\n` +
    f.block.replace(/url\(https:[^)]+\)/, `url(../fonts/${names.get(f.url)})`)
);

fs.writeFileSync(
  path.join(SITE, "css", "fonts.css"),
  "/* Self-hosted subsets (cyrillic + latin) of Prata, Manrope and IBM Plex Mono.\n" +
    "   Generated by scripts/fetch-fonts.mjs so the page makes no third-party request. */\n\n" +
    out.join("\n\n") +
    "\n"
);

console.log(`fonts: ${names.size} files · ${faces.length} faces`);
